### ISSUE TITLE
Test network communication

### ISSUE THREAD

**Issue by Superritchman** [ManticSic/efiaIRC#11]
Send a few test messages and test the communication

**Comment by ManticSic** [comment]
reicht es aus einen send und einen receive client zu entwickeln, oder müssen es zwei rechner in einem netz sein, die miteinander kommunizieren?

**Comment by Superritchman** [comment]
Habe gerade ein Testprojekt geschrieben und es ist schon im Network-Constructor auf die Schnauze gefallen :D
Zur Frage: Bin mir nicht sicher ob man die eigenen Multicast-Pakete bekommt (müssten wir ausprobieren sobald die Sockets etabliert sind)

**Comment by ManticSic** [comment]
Wie läufts?

**Comment by ManticSic** [comment]
TestClient funktioniert bei mir lokal (Senden und empfangen). müssen dann mal in einem Netzwerk mit mehr als einem Rechner schauen. Derzeit keinen zweiten zuhause zur verfügung zum testen...
